version: "3.3"
services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - .:/code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./docker
    volumes:
      - .:/code
  db:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
